pipeline {
 parameters {
        string(name: 'Greeting', defaultValue: 'Hello', description: 'How should I greet the world?')
    }
  
  agent any
  stages {
    stage('Build') {
      steps {
        echo "building UAT"
        
      }
    }

  }
}
